# Generated by Django 5.1.8 on 2025-04-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vector_db",
            field=models.IntegerField(
                choices=[(0, "Pinecone"), (1, "Weaviate")],
                default=1,
                help_text="Vector database to use for this user's data",
                verbose_name="Vector Database",
            ),
        ),
    ]
