# Generated by Django 5.1.8 on 2025-06-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_accesscodegroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_code_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Access code group this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.accesscodegroup",
            ),
        ),
    ]
