# Generated by Django 5.1.12 on 2026-07-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_merge_20260521_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chunk_size',
            field=models.IntegerField(default=1500, help_text='Size of text chunks for document processing.', verbose_name='Chunk Size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='overlap_size',
            field=models.IntegerField(default=180, help_text='Size of overlap between text chunks', verbose_name='Overlap Size'),
        ),
    ]
