# Generated by Django 5.1.8 on 2025-05-06 18:30

from django.db import migrations

def create_wallets(apps, schema_editor):
    User = apps.get_model("users", "User")
    Wallet = apps.get_model("billing", "Wallet")
    for user in User.objects.all():
        Wallet.objects.get_or_create(user=user, defaults={"balance": 5})

class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("users", "0003_user_default_prompt"),
    ]

    operations = [
        migrations.RunPython(create_wallets, reverse_code=migrations.RunPython.noop),
    ]
