# Generated by Django 5.1.8 on 2025-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_transaction_llm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Transaction amount in USD",
                max_digits=10,
                verbose_name="Amount",
            ),
        ),
    ]
