# Generated by Django 5.1.12 on 2026-08-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0021_add_usage_breakdown_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="What this call would have cost at DARE's own rates, for usage reporting only. Set on externally-billed calls, where `amount` is zero because the wallet was never debited. Null when no DARE-side model matches.",
                max_digits=10,
                null=True,
                verbose_name="Reference Amount",
            ),
        ),
    ]
