# Generated by Django 5.1.12 on 2026-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_transaction_reference_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='litellmkey',
            name='memory_model',
            field=models.CharField(blank=True, default='', help_text="Model this proxy serves that should write memory. Blank falls back to DARE's configured memory model, billed to DARE.", max_length=255, verbose_name='Memory Model'),
        ),
        migrations.AddField(
            model_name='litellmkey',
            name='title_model',
            field=models.CharField(blank=True, default='', help_text="Model this proxy serves that should name conversations. Blank falls back to DARE's configured title model, which a proxy may not serve under the same identifier.", max_length=255, verbose_name='Title Model'),
        ),
    ]
