# Generated by Django 5.1.12 on 2026-08-25 04:54

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0022_transaction_reference_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteLLMSpend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_reference_amount",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Cumulative reference cost of calls this user made through this key, in USD. Reporting only — never charged.",
                        max_digits=12,
                        verbose_name="Total Reference Amount",
                    ),
                ),
                (
                    "call_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of calls counted into the total.",
                        verbose_name="Call Count",
                    ),
                ),
                (
                    "litellm_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spend_records",
                        to="billing.litellmkey",
                        verbose_name="LiteLLM Key",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litellm_spend",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "LiteLLM Spend",
                "verbose_name_plural": "LiteLLM Spend",
                "unique_together": {("user", "litellm_key")},
            },
        ),
    ]
