# Generated by Django 5.1.12 on 2026-08-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0023_litellmkey_memory_model_litellmkey_title_model"),
        ("billing", "0024_backfill_litellm_spend"),
    ]

    operations = []
