# Generated by Django 5.1.12 on 2026-09-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_merge_20260825_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cached_input_tokens',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Input tokens the provider served from its prompt cache', null=True, verbose_name='Cached Input Tokens'),
        ),
    ]
