# Generated by Django 5.1.12 on 2026-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0027_unify_litellm_background_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupwallet",
            name="litellm_member_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Most each member may spend, in total, through this group's LiteLLM keys. Measured at DARE's reference rates. Null means no limit.",
                max_digits=10,
                null=True,
                verbose_name="LiteLLM Spend Limit per Member (USD)",
            ),
        ),
        migrations.AddField(
            model_name="groupwallet",
            name="refill_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Scheduled refills top each member up to this balance and never past it; the group budget is charged only for what is added. Null means inherit the system default.",
                max_digits=10,
                null=True,
                verbose_name="Group Refill Cap (USD)",
            ),
        ),
        migrations.AddField(
            model_name="litellmkey",
            name="gateway_max_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="The key's hard budget as the gateway reports it. Null when unset.",
                max_digits=12,
                null=True,
                verbose_name="Gateway-Reported Budget (USD)",
            ),
        ),
        migrations.AddField(
            model_name="litellmkey",
            name="gateway_reported_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a gateway response last reported this key's spend.",
                null=True,
                verbose_name="Gateway Report Received At",
            ),
        ),
        migrations.AddField(
            model_name="litellmkey",
            name="gateway_spend",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="The key's total spend as the LiteLLM gateway reports it in response headers. The gateway's own figure, used to check DARE's estimates. Keeps the highest value seen, because replicas can report stale totals.",
                max_digits=12,
                null=True,
                verbose_name="Gateway-Reported Spend (USD)",
            ),
        ),
        migrations.AddField(
            model_name="systemrefillpolicy",
            name="refill_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Scheduled refills top a wallet up to this balance and never past it. Blank means the refill amount is the ceiling, so balances never stack.",
                max_digits=10,
                null=True,
                verbose_name="Default Refill Cap (USD)",
            ),
        ),
        migrations.AddField(
            model_name="userrefilloverride",
            name="litellm_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Custom limit on this user's total spend through their group's LiteLLM keys. Null means inherit the group's per-member limit.",
                max_digits=10,
                null=True,
                verbose_name="LiteLLM Spend Limit (USD)",
            ),
        ),
        migrations.AddField(
            model_name="userrefilloverride",
            name="refill_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Custom balance ceiling for scheduled refills. Null means inherit from group/system.",
                max_digits=10,
                null=True,
                verbose_name="Refill Cap (USD)",
            ),
        ),
    ]
