# Generated by Django 5.1.12 on 2026-09-26 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0103_update_claude_sonnet_5_rates"),
        ("files", "0027_vectorindexattempt_finished_at"),
        ("libraries", "0003_catalog_backend_weaviate"),
        ("prompts", "0006_prompt_forked_from_user"),
        ("workflows", "0074_workflow_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(help_text="Display name.", max_length=120)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("folder", "Folder"),
                            ("book", "Book"),
                            ("flask", "Flask"),
                            ("briefcase", "Briefcase"),
                            ("graduation", "Graduation cap"),
                            ("chart", "Chart"),
                            ("code", "Code"),
                            ("lightbulb", "Lightbulb"),
                            ("pen", "Pen"),
                            ("globe", "Globe"),
                            ("heart", "Heart"),
                            ("calendar", "Calendar"),
                        ],
                        default="folder",
                        help_text="Icon shown next to the project name.",
                        max_length=24,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short note on what the project is for.",
                        max_length=500,
                    ),
                ),
                (
                    "web_search_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="New project chats start with web search on.",
                    ),
                ),
                (
                    "artifacts_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="New project chats start with artifacts on.",
                    ),
                ),
                (
                    "memory_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="New project chats start with memory on.",
                    ),
                ),
                (
                    "memory_scope",
                    models.CharField(
                        choices=[
                            ("all", "All memories"),
                            ("project", "Only memories from this project's chats"),
                        ],
                        default="all",
                        help_text="Whether project chats recall all memories or only those learned in this project's chats. Read on every turn.",
                        max_length=16,
                    ),
                ),
                (
                    "default_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Model pre-selected in new project chats.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_projects",
                        to="conversations.llm",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sources pre-selected for retrieval in new project chats.",
                        related_name="personal_projects",
                        to="files.file",
                    ),
                ),
                (
                    "folders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Source folders whose current files are pre-selected in new project chats.",
                        related_name="personal_projects",
                        to="files.folder",
                    ),
                ),
                (
                    "libraries",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Shared libraries pre-selected in new project chats.",
                        related_name="personal_projects",
                        to="libraries.sharedlibrary",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        help_text="The project's instructions: a prompt from the user's library, pre-selected in new project chats.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_projects",
                        to="prompts.prompt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflows",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Workflows pinned to this project for quick access.",
                        related_name="personal_projects",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "personal project",
                "verbose_name_plural": "personal projects",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="projects_pe_user_id_4b434a_idx",
                    )
                ],
            },
        ),
    ]
