# Generated by Django 5.1.7 on 2025-03-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_seed_llm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='is_reasoning',
            field=models.BooleanField(default=True, help_text='Whether the model supports reasoning.'),
        ),
    ]
