# Generated by Django 5.1.7 on 2025-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_llm_is_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='is_reasoning',
            field=models.BooleanField(default=False, help_text='Whether the model supports reasoning.'),
        ),
    ]
