# Generated by Django 5.1.6 on 2025-03-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0005_alter_llm_is_reasoning"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="The LLM used to generate this message (null for user messages).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="conversations.llm",
            ),
        ),
    ]
