# Generated by Django 5.1.6 on 2025-04-12 15:41

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0006_message_llm"),
        ("files", "0004_file_job_id_file_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "text",
                    models.TextField(
                        help_text="The text content of the snippet (chunk)."
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="The similarity score of the snippet to the query."
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="The index of the chunk in the original file."
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The file this snippet belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to="files.file",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this snippet was retrieved for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
