# Generated by Django 5.1.8 on 2025-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0014_conversation_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="dislike_feedback",
            field=models.TextField(
                blank=True,
                help_text="Optional feedback text when user dislikes a message.",
                null=True,
            ),
        ),
    ]
