# Generated by Django 5.1.8 on 2025-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0015_message_dislike_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="history_limit",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Maximum number of messages to include in conversation history.",
            ),
        ),
    ]
