# Generated by Django 5.1.11 on 2025-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0017_message_cost"),
        ("files", "0007_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associated with this message",
                related_name="chat_messages",
                to="files.tag",
            ),
        ),
    ]
