# Generated by Django 5.1.11 on 2025-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0018_message_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="dislike_feedback",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_disliked",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="message",
            name="feedback_text",
            field=models.TextField(
                blank=True,
                help_text="Optional feedback text provided by the user.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="feedback_type",
            field=models.CharField(
                blank=True,
                choices=[("like", "Like"), ("dislike", "Dislike")],
                help_text="Type of feedback provided by the user (like/dislike).",
                max_length=10,
                null=True,
            ),
        ),
    ]
