# Generated by Django 5.1.12 on 2025-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0026_llm_supports_vision"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="web_search_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable real-time web search for up-to-date information.",
            ),
        ),
    ]
