# Generated by Django 5.1.12 on 2026-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0056_add_react_artifact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('document', 'Document'), ('code', 'Code'), ('diagram', 'Diagram'), ('chart', 'Chart'), ('react', 'React Component')], default='document', help_text='Type of artifact (document, code, diagram).', max_length=20),
        ),
    ]
