# Generated by Django 5.1.12 on 2026-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0075_seed_modern_llm_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="selected_library_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of selected shared-library IDs for this conversation.",
            ),
        ),
    ]
