# Generated by Django 5.1.12 on 2026-06-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0076_conversation_selected_library_ids"),
        ("files", "0015_file_syftbox_etag"),
        ("libraries", "0003_catalog_backend_weaviate"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="library",
            field=models.ForeignKey(
                blank=True,
                help_text="The shared library this snippet belongs to (null for the user's own files).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to="libraries.sharedlibrary",
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="source_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable source for library snippets (e.g. 'Fields Paul p.78').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="file",
            field=models.ForeignKey(
                blank=True,
                help_text="The file this snippet belongs to (null for shared-library snippets).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to="files.file",
            ),
        ),
    ]
