# Generated by Django 5.1.12 on 2026-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0077_snippet_library_snippet_source_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="retrieval_trace",
            field=models.JSONField(
                blank=True,
                help_text="Per-stage RAG pipeline trace (query analysis, hybrid, rerank, MMR, grounding) for the retrieval-trace UI.",
                null=True,
            ),
        ),
    ]
