# Generated by Django 5.1.12 on 2026-07-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0078_message_retrieval_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="rag_mode",
            field=models.CharField(
                choices=[("naive", "Naive RAG"), ("advanced", "Advanced RAG")],
                default="advanced",
                help_text="Retrieval mode for selected vector databases and shared libraries.",
                max_length=20,
            ),
        ),
    ]
