# Generated by Django 5.1.12 on 2026-07-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0077_seed_claude_sonnet_5'),
        ('conversations', '0079_conversation_rag_mode'),
    ]

    operations = [
    ]
