# Generated by Django 5.1.12 on 2026-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0080_merge_20260707_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='rag_mode',
            field=models.CharField(choices=[('naive', 'Naive RAG'), ('advanced', 'Advanced RAG'), ('agentic', 'Agentic RAG')], default='advanced', help_text='Retrieval mode for selected vector databases and shared libraries.', max_length=20),
        ),
    ]
