# Generated by Django 5.1.12 on 2026-07-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0081_alter_conversation_rag_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='usage_details',
            field=models.JSONField(blank=True, help_text='Per-round token/cost breakdown for multi-round tool responses; summed values live in input_tokens/output_tokens/cost.', null=True),
        ),
        migrations.AddField(
            model_name='messagetoolcall',
            name='round_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tool-loop round this call executed in (1-based); 0 for rows persisted before rounds existed.'),
        ),
    ]
