# Generated by Django 5.1.15 on 2026-07-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0078_seed_gpt_5_6_family"),
        ("conversations", "0081_alter_conversation_rag_mode"),
    ]

    operations = []
