# Generated by Django 5.1.12 on 2026-07-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0082_message_usage_details_messagetoolcall_round_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="context_trace",
            field=models.JSONField(
                blank=True,
                help_text="Timed context-assembly stages for the turn (prompt, files, retrieval, memory, history) for the context-trace UI.",
                null=True,
            ),
        ),
    ]
