# Generated by Django 5.1.15 on 2026-08-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0088_add_pdf_artifact_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'mmlu_pro', 'aaii')",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'MMLU-Pro')", max_length=100
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name for tooltips (e.g., 'Massive Multitask Language Understanding Pro')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this benchmark measures"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Category: knowledge, reasoning, coding, safety, composite, multimodal",
                        max_length=150,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="Leaderboard or paper URL"),
                ),
                (
                    "methodology_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on scoring methodology, variants, caveats",
                    ),
                ),
                ("higher_is_better", models.BooleanField(default=True)),
                (
                    "scale",
                    models.CharField(
                        default="percentage",
                        help_text="Scale type: percentage, index, elo, raw",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Benchmark",
                "verbose_name_plural": "Benchmarks",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="llm",
            name="reasoning_level",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("cost_predictable", "Cost Predictable"),
                    ("cost_unconstrained", "Cost Unconstrained"),
                ],
                default="none",
                help_text="How likely the model's reasoning is to produce surprising levels of token usage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="modelcarddata",
            name="arena_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modelcarddata",
            name="benchmark_scores",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modelcarddata",
            name="external_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cached metadata from Wikidata/other sources (publication_date, param_count, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="modelcarddata",
            name="reasoning_level",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("cost_predictable", "Cost Predictable"),
                    ("cost_unconstrained", "Cost Unconstrained"),
                ],
                default="none",
                help_text="How likely the model's reasoning is to produce surprising levels of token usage. cost_predictable: Reasoning depth stays proportional to the task; token use stays predictable. cost_unconstrained: Sets its own reasoning depth. Simple prompts can generate large token counts without warning.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="modelcarddata",
            name="wikidata_id",
            field=models.CharField(
                blank=True,
                help_text="Wikidata QID (e.g., Q113741966 for GPT-4)",
                max_length=20,
                null=True,
            ),
        ),
    ]
