# Generated by Django 5.1.12 on 2026-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0089_model_card_data_streams_and_reasoning_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='memory_enabled',
            field=models.BooleanField(default=False, help_text="Enable cross-conversation memory. Gates BOTH halves of the pipeline: retrieved memories are injected into this conversation's prompts, and its completed turns are read by the memory writer. Off means nothing is recalled and nothing is written down."),
        ),
    ]
