# Generated by Django 5.1.12 on 2026-08-16 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0089_model_card_data_streams_and_reasoning_level"),
        ("workflows", "0072_stepnodedata_enable_artifacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="workflow_run_step",
            field=models.ForeignKey(
                blank=True,
                help_text="The workflow run step this artifact belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="workflows.workflowrunstep",
            ),
        ),
        migrations.AddField(
            model_name="artifactgroup",
            name="workflow_run_step",
            field=models.ForeignKey(
                blank=True,
                help_text="The workflow run step this artifact group belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifact_groups",
                to="workflows.workflowrunstep",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="The conversation this artifact belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="conversations.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="artifactgroup",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="The conversation this artifact group belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifact_groups",
                to="conversations.conversation",
            ),
        ),
    ]
