# Generated by Django 5.1.12 on 2026-08-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0090_add_memory_enabled_to_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='memory_write_data',
            field=models.JSONField(blank=True, help_text='What the memory writer decided after this turn: counts plus every ledger entry including refusals. Written by the background job after the reply is finished, so it arrives later than the rest of the message — and is stored rather than only pushed, so the panel survives a reload.', null=True),
        ),
    ]
