# Generated by Django 5.1.12 on 2026-08-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0092_message_memory_write_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="last_memory_extracted_at",
        ),
    ]
