# Generated by Django 5.1.12 on 2026-09-01 22:05

import django.core.validators
from decimal import Decimal

from django.db import migrations, models


# Cached-input price as a fraction of the model's own input rate, from the
# providers' published cache pricing (checked 2026-09-02):
#   OpenAI    developers.openai.com/api/docs/pricing
#   Anthropic platform.claude.com/docs/en/about-claude/pricing
#   Google    ai.google.dev/gemini-api/docs/pricing
# Deriving from the row's input rate keeps the value correct in every
# environment regardless of the absolute prices configured there.
#
#   OpenAI:    gpt-4o family and o1/o3-mini 50%, gpt-4.1 family and o3/o4 25%,
#              gpt-5 family 10%
#   Anthropic: 10% on every model except Fable 5.1 / Mythos 5.1 at 2.5%
#   Google:    10% on every Gemini model
#
# Longest prefix wins. Models with no entry (image, audio, gpt-3.5, unknown
# custom rows) are left untouched and bill cached tokens at the input rate.
CACHE_DISCOUNT_BY_PREFIX = {
    "gpt-4o": Decimal("0.50"),
    "gpt-4.1": Decimal("0.25"),
    "gpt-5": Decimal("0.10"),
    "o1": Decimal("0.50"),
    "o3-mini": Decimal("0.50"),
    "o3": Decimal("0.25"),
    "o4": Decimal("0.25"),
    "claude-fable-5-1": Decimal("0.025"),
    "claude-mythos-5-1": Decimal("0.025"),
    "claude": Decimal("0.10"),
    "gemini": Decimal("0.10"),
}

EXCLUDED_PREFIXES = ("dall-e", "whisper", "gpt-4o-transcribe", "gpt-image")


def _discount_for(identifier: str):
    ident = identifier.lower()
    if ident.startswith(EXCLUDED_PREFIXES):
        return None
    match = max(
        (prefix for prefix in CACHE_DISCOUNT_BY_PREFIX if ident.startswith(prefix)),
        key=len,
        default=None,
    )
    return CACHE_DISCOUNT_BY_PREFIX[match] if match else None


def seed_cached_input_rates(apps, schema_editor):
    llm_model = apps.get_model("conversations", "LLM")
    rows = llm_model.objects.filter(
        cached_input_token_rate_per_million__isnull=True,
        input_token_rate_per_million__gt=0,
    )
    for llm in rows:
        discount = _discount_for(llm.identifier)
        if discount is None:
            continue
        llm.cached_input_token_rate_per_million = (
            llm.input_token_rate_per_million * discount
        ).quantize(Decimal("0.0001"))
        llm.save(update_fields=["cached_input_token_rate_per_million"])


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0096_editorial_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='cached_input_token_rate_per_million',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost per million prompt-cached input tokens in USD. Leave empty to bill cached tokens at the full input rate.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(seed_cached_input_rates, migrations.RunPython.noop),
    ]
