# Generated by Django 5.1.12 on 2026-09-01 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0096_editorial_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='cached_input_token_rate_per_million',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost per million prompt-cached input tokens in USD. Leave empty to bill cached tokens at the full input rate.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
