# Generated by Django 5.1.12 on 2026-09-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0103_update_claude_sonnet_5_rates'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Personal project this conversation is filed under, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='projects.personalproject'),
        ),
    ]
