# Generated by Django 5.1.12 on 2026-06-21 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier, e.g. 'civil-war-pensions'.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name.", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="What the corpus contains."
                    ),
                ),
                (
                    "curator",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who curated/owns the dataset (e.g. 'CMU').",
                        max_length=255,
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("weaviate", "Weaviate"), ("pinecone", "Pinecone")],
                        default="pinecone",
                        help_text="Vector store that physically holds the corpus.",
                        max_length=20,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        help_text="Vector-store namespace holding the corpus. Derived from slug if blank.",
                        max_length=255,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-large",
                        help_text="Model the corpus was embedded with. Must match the query embedder.",
                        max_length=100,
                    ),
                ),
                (
                    "dims",
                    models.PositiveIntegerField(
                        default=3072, help_text="Vector dimensionality."
                    ),
                ),
                (
                    "object_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Indexed chunk count, or null if unknown.",
                        null=True,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="False for 'coming soon' catalog entries.",
                    ),
                ),
                (
                    "source_attribution",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Attribution / license text to surface with results.",
                    ),
                ),
            ],
            options={
                "verbose_name": "shared library",
                "verbose_name_plural": "shared libraries",
                "ordering": ["-is_available", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserLibraryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "library",
                    models.ForeignKey(
                        help_text="Library that was added.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_entries",
                        to="libraries.sharedlibrary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who added the library.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user library access",
                "verbose_name_plural": "user library access",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "library"), name="unique_user_library"
                    )
                ],
            },
        ),
    ]
