# Generated by Django 5.1.6 on 2025-03-20 15:28

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prompts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the workflow.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the workflow."),
                ),
                (
                    "operation_mode",
                    models.CharField(
                        choices=[("serial", "Serial"), ("parallel", "Parallel")],
                        default="serial",
                        help_text="Mode of operation (Serial or Parallel).",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this workflow.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the step in the workflow."
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        help_text="Prompt associated with this step.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_steps",
                        to="prompts.prompt",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this step belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "order"],
                "unique_together": {("workflow", "order")},
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
