# Generated by Django 5.1.6 on 2025-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="step",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="operation_mode",
        ),
        migrations.AddField(
            model_name="workflow",
            name="mode",
            field=models.IntegerField(
                choices=[(1, "Serial"), (2, "Parallel")],
                default=1,
                help_text="Mode of operation (Serial or Parallel).",
                max_length=20,
            ),
        ),
    ]
