# Generated by Django 5.1.6 on 2025-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_remove_step_is_active_remove_step_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="mode",
            field=models.IntegerField(
                choices=[(1, "Serial"), (2, "Parallel")],
                default=1,
                help_text="Mode of operation (Serial or Parallel).",
            ),
        ),
    ]
