# Generated by Django 5.1.6 on 2025-03-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_alter_workflow_mode"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="step",
            managers=[],
        ),
    ]
