# Generated by Django 5.1.6 on 2025-03-20 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0004_alter_step_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={"ordering": ["order"]},
        ),
        migrations.AlterUniqueTogether(
            name="step",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="step",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="User who owns this step.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflow",
            name="steps",
            field=models.ManyToManyField(
                blank=True,
                help_text="Steps included in this workflow",
                related_name="workflows",
                to="workflows.step",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Default order of the step."
            ),
        ),
        migrations.RemoveField(
            model_name="step",
            name="workflow",
        ),
    ]
