# Generated by Django 5.1.8 on 2025-06-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0008_step_max_tokens_step_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="document_similarity_threshold",
            field=models.FloatField(
                default=0.2,
                help_text="Similarity threshold for document retrieval in this step.",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="is_embeddings",
            field=models.BooleanField(
                default=False,
                help_text="Whether to use embeddings for context retrieval. If False, uses full file content.",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="max_context_snippets",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Maximum number of context snippets to retrieve for this step.",
            ),
        ),
    ]
