# Generated by Django 5.1.11 on 2025-06-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0009_step_document_similarity_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Original workflow this was cloned from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="workflows.workflow",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Version number of the workflow. Increments when cloned.",
            ),
        ),
    ]
