# Generated by Django 5.1.11 on 2025-06-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0010_workflow_parent_workflow_version"),
        ("workflows", "0011_remove_step_file_remove_step_is_embeddings"),
    ]

    operations = []
