# Generated by Django 5.1.11 on 2025-09-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0018_aggregatornodedata_chatoutputnodedata_startnodedata_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowrunstep",
            name="step",
        ),
        migrations.AddField(
            model_name="workflowrunstep",
            name="step_node",
            field=models.ForeignKey(
                help_text="Step node being executed.",
                limit_choices_to={"node_type": "step"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.workflownode",
            ),
        ),
        migrations.DeleteModel(
            name="Step",
        ),
    ]
