# Generated by Django 5.1.12 on 2025-09-28 13:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_workflowrunstep_references(apps, schema_editor):
    """
    Migrate WorkflowRunStep references from old Step model to new WorkflowNode model.
    This function maps old step_id references to the corresponding step nodes created during migration.
    """
    WorkflowRunStep = apps.get_model('workflows', 'WorkflowRunStep')
    WorkflowNode = apps.get_model('workflows', 'WorkflowNode')

    # Get all WorkflowRunStep instances that need migration
    run_steps = WorkflowRunStep.objects.all()

    for run_step in run_steps:
        if hasattr(run_step, 'step_id') and run_step.step_id:
            # Find the corresponding WorkflowNode for this step
            try:
                # The migration script creates step nodes with node_id = f'step-{step.order}'
                # We need to find the step node that corresponds to this order
                step_node = WorkflowNode.objects.filter(
                    workflow=run_step.workflow_run.workflow,
                    node_type='step',
                    node_id=f'step-{run_step.order}'
                ).first()

                if step_node:
                    run_step.step_node_id = step_node.id
                    run_step.save(update_fields=['step_node_id'])
                    print(f"Migrated WorkflowRunStep {run_step.id} to use step_node {step_node.id}")
                else:
                    print(f"Warning: Could not find step node for WorkflowRunStep {run_step.id} with order {run_step.order}")
            except Exception as e:
                print(f"Error migrating WorkflowRunStep {run_step.id}: {e}")


def reverse_migrate_workflowrunstep_references(apps, schema_editor):
    """
    Reverse migration - this is complex since we'd need to recreate Step instances.
    For now, we'll just clear the step_node_id field.
    """
    WorkflowRunStep = apps.get_model('workflows', 'WorkflowRunStep')
    WorkflowRunStep.objects.all().update(step_node_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_auto_20250928_1342'),
    ]

    operations = [
        # Add the new step_node field (nullable initially)
        migrations.AddField(
            model_name='workflowrunstep',
            name='step_node',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='workflows.workflownode',
                limit_choices_to={'node_type': 'step'},
                help_text="Step node being executed."
            ),
        ),

        # Run the data migration to populate step_node_id from step_id
        migrations.RunPython(
            migrate_workflowrunstep_references,
            reverse_migrate_workflowrunstep_references
        ),

        # Remove the old step field (commenting out for safety - can be done later)
        # migrations.RemoveField(
        #     model_name='workflowrunstep',
        #     name='step',
        # ),
    ]