# Generated by Django 5.1.11 on 2025-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0019_remove_workflowrunstep_step_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="workflow",
            managers=[],
        ),
        migrations.AlterField(
            model_name="workflowrunstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                help_text="Current status of this step.",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="WorkflowStepSnippet",
        ),
    ]
