# Generated by Django 5.1.11 on 2025-09-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0020_alter_workflow_managers_alter_workflowrunstep_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionalNodeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_prompt",
                    models.TextField(
                        default="Evaluate the input and choose the appropriate route.",
                        help_text="Custom evaluation prompt for routing decision",
                    ),
                ),
                (
                    "route_a_name",
                    models.CharField(
                        default="Route A",
                        help_text="Name for route A output",
                        max_length=100,
                    ),
                ),
                (
                    "route_b_name",
                    models.CharField(
                        default="Route B",
                        help_text="Name for route B output",
                        max_length=100,
                    ),
                ),
                (
                    "route_a_description",
                    models.TextField(
                        blank=True, help_text="Optional description for route A"
                    ),
                ),
                (
                    "route_b_description",
                    models.TextField(
                        blank=True, help_text="Optional description for route B"
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(
                        help_text="Step number for execution ordering"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
