# Generated by Django 5.1.11 on 2025-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0021_conditionalnodedata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AggregatorNodeData",
        ),
        migrations.AlterField(
            model_name="workflownode",
            name="node_type",
            field=models.CharField(
                help_text="React Flow node type (node.type): step, start, chatOutput, conditional",
                max_length=100,
            ),
        ),
    ]
