# Generated by Django 5.1.12 on 2025-09-30
# Safety cleanup migration - removes title/description/mode fields if they still exist
# This handles environments where old versions of migration 0020 ran that didn't remove these fields

from django.db import migrations


def get_table_columns(cursor, db_vendor, table_name):
    """Helper function to get table columns for any database"""
    if db_vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info({table_name});")
        return {row[1] for row in cursor.fetchall()}
    else:
        # PostgreSQL, MySQL, etc.
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = %s
        """, [table_name])
        return {row[0] for row in cursor.fetchall()}


def cleanup_legacy_fields(apps, schema_editor):
    """
    Remove title/description/mode fields from Workflow table if they still exist.
    This is a safety net for environments where migration 0020 didn't fully clean up.
    """
    db_vendor = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        existing_columns = get_table_columns(cursor, db_vendor, 'workflows_workflow')

    legacy_fields = {'title', 'description', 'mode'}
    fields_to_remove = legacy_fields & existing_columns

    if not fields_to_remove:
        print("✅ No legacy fields found - table already clean")
        return

    print(f"⚠️  Found legacy fields still present: {', '.join(fields_to_remove)}")
    print("   Cleaning them up now...")

    if db_vendor == 'sqlite':
        # SQLite - recreate table
        with schema_editor.connection.cursor() as cursor:
            # Get all columns
            all_columns_data = cursor.execute("PRAGMA table_info(workflows_workflow);").fetchall()
            all_columns = [row[1] for row in all_columns_data]

            # Keep only non-legacy columns
            keep_columns = [col for col in all_columns if col not in legacy_fields]
            keep_columns_str = ', '.join(keep_columns)

            # Define expected final schema
            expected_schema = {
                'id': 'INTEGER PRIMARY KEY AUTOINCREMENT',
                'created_at': 'datetime NOT NULL',
                'updated_at': 'datetime NOT NULL',
                'is_active': 'bool NOT NULL',
                'is_deleted': 'bool NOT NULL',
                'user_id': 'bigint NOT NULL REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED',
                'version': 'integer unsigned NOT NULL CHECK (version >= 0)',
                'parent_id': 'bigint REFERENCES workflows_workflow(id) DEFERRABLE INITIALLY DEFERRED',
                'viewport_x': 'REAL NOT NULL',
                'viewport_y': 'REAL NOT NULL',
                'viewport_zoom': 'REAL NOT NULL',
            }

            # Build CREATE statement with only kept columns
            new_table_columns = []
            for col in keep_columns:
                if col in expected_schema:
                    new_table_columns.append(f"{col} {expected_schema[col]}")

            create_statement = f"""
                CREATE TABLE workflows_workflow_new (
                    {', '.join(new_table_columns)}
                );
            """

            cursor.execute(create_statement)
            cursor.execute(f"""
                INSERT INTO workflows_workflow_new ({keep_columns_str})
                SELECT {keep_columns_str} FROM workflows_workflow;
            """)
            cursor.execute("DROP TABLE workflows_workflow;")
            cursor.execute("ALTER TABLE workflows_workflow_new RENAME TO workflows_workflow;")
    else:
        # PostgreSQL - use ALTER TABLE DROP COLUMN
        with schema_editor.connection.cursor() as cursor:
            for field in fields_to_remove:
                cursor.execute(f"ALTER TABLE workflows_workflow DROP COLUMN {field};")

    print(f"✅ Cleaned up legacy fields: {', '.join(fields_to_remove)}")


def reverse_cleanup(apps, schema_editor):
    """
    Reverse is a no-op - we don't want to add legacy fields back.
    """
    print("⚠️  Reverse migration - no action taken (legacy fields remain removed)")


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_add_viewport_fields'),
    ]

    operations = [
        migrations.RunPython(cleanup_legacy_fields, reverse_cleanup),
    ]
