# Generated by Django 5.1.12 on 2026-08-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0016_file_document_model_file_extracted_text_and_more"),
        ("libraries", "0003_catalog_backend_weaviate"),
        ("workflows", "0066_add_use_previous_context_to_stepnodedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrunstep",
            name="retrieval_trace",
            field=models.JSONField(
                blank=True,
                help_text="Per-stage RAG pipeline trace (query analysis, hybrid, rerank, MMR, grounding) for the retrieval-trace UI.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowstepsnippet",
            name="library",
            field=models.ForeignKey(
                blank=True,
                help_text="The shared library this snippet belongs to (null for the user's own files).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_step_snippets",
                to="libraries.sharedlibrary",
            ),
        ),
        migrations.AddField(
            model_name="workflowstepsnippet",
            name="source_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable source for library snippets (e.g. 'Fields Paul p.78').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepsnippet",
            name="file",
            field=models.ForeignKey(
                blank=True,
                help_text="The file this snippet belongs to (null for library snippets).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_step_snippets",
                to="files.file",
            ),
        ),
    ]
