# Generated by Django 5.1.12 on 2026-08-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0003_catalog_backend_weaviate"),
        ("workflows", "0067_workflowrunstep_retrieval_trace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepnodedata",
            name="libraries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Shared libraries to retrieve context from for this step",
                related_name="step_nodes",
                to="libraries.sharedlibrary",
            ),
        ),
        migrations.AddField(
            model_name="stepnodedata",
            name="rag_mode",
            field=models.CharField(
                choices=[
                    ("naive", "Naive RAG"),
                    ("advanced", "Advanced RAG"),
                    ("agentic", "Agentic RAG"),
                ],
                default="naive",
                help_text="Retrieval mode for this step's document context (naive/advanced/agentic)",
                max_length=20,
            ),
        ),
    ]
