# Generated by Django 5.1.12 on 2026-08-16 00:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0068_stepnodedata_libraries_stepnodedata_rag_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrunstep",
            name="context_trace",
            field=models.JSONField(
                blank=True,
                help_text="Timed context-assembly stages for the step's LLM turn (prompt, files, retrieval) for the context-trace UI.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowStepToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tool_call_id",
                    models.CharField(
                        help_text="Unique ID from LLM (e.g., 'call_abc123' or 'toolu_abc123').",
                        max_length=100,
                    ),
                ),
                (
                    "server_slug",
                    models.CharField(
                        help_text="Concrete tool server/provider slug (e.g., 'dare', 'slack').",
                        max_length=100,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("dare", "DARE"),
                            ("mcp", "MCP"),
                            ("provider", "Provider"),
                        ],
                        default="mcp",
                        help_text="Execution origin: DARE internal, MCP external, or provider-native.",
                        max_length=20,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Name of the tool (e.g., 'search_documents').",
                        max_length=200,
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        default=dict, help_text="Arguments passed to the tool."
                    ),
                ),
                (
                    "round_index",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Tool-loop round this call executed in (1-based).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the tool call.",
                        max_length=30,
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Bounded JSON result text from tool execution.",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed.",
                        null=True,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the tool was executed.", null=True
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Wall-clock execution time of the tool call in milliseconds.",
                    ),
                ),
                (
                    "workflow_run_step",
                    models.ForeignKey(
                        help_text="The workflow run step whose LLM turn requested this tool call.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="workflows.workflowrunstep",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_run_step", "status"],
                        name="wstc_step_status_idx",
                    ),
                    models.Index(fields=["tool_call_id"], name="wstc_call_id_idx"),
                ],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
