# Generated by Django 5.1.12 on 2026-08-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0069_workflowrunstep_context_trace_workflowsteptoolcall"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="workflowsteptoolcall",
            managers=[],
        ),
    ]
