# Generated by Django 5.1.12 on 2026-08-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0013_alter_mcpserver_managers"),
        ("workflows", "0070_alter_workflowsteptoolcall_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepnodedata",
            name="enable_web_fetch",
            field=models.BooleanField(
                default=False,
                help_text="If true, enable provider web fetch (explicit URLs/PDFs) for this step's LLM",
            ),
        ),
        migrations.AddField(
            model_name="stepnodedata",
            name="mcp_servers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Connected MCP servers whose tools this step's LLM may call",
                related_name="step_nodes",
                to="mcp.mcpserver",
            ),
        ),
    ]
