# Generated by Django 5.1.12 on 2026-08-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0071_stepnodedata_enable_web_fetch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepnodedata",
            name="enable_artifacts",
            field=models.BooleanField(
                default=False,
                help_text="If true, expose artifact-creating tools (charts, diagrams, docs) to this step's LLM",
            ),
        ),
    ]
