# Generated by Django 5.1.6 on 2025-04-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_logs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="is_deleted",
        ),
    ]
