# Generated by Django 5.1.12 on 2026-08-11 00:29

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0088_add_pdf_artifact_type'),
        ('memory', '0002_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('fact', 'Fact'), ('procedure', 'Procedure')], help_text='A fact about the person, or a rule for a situation.', max_length=16)),
                ('key', models.CharField(blank=True, default='', help_text="Qualified topic key. Two rows of one kind sharing a key cannot both be true — that collision is what turns 'I moved' into a retirement instead of a contradiction.", max_length=255)),
                ('text', models.TextField(help_text='The statement, third person, standalone.')),
                ('state', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('held', 'Held')], default='active', help_text='active / superseded / held. Retire, never delete.', max_length=16)),
                ('sensitivity', models.CharField(choices=[('none', 'None'), ('health', 'Health'), ('safety', 'Safety'), ('third-party', 'Third party')], default='none', help_text='health is gated (held); safety is never gated.', max_length=16)),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='A stated end date, or the day a replacement arrived. Null on slot topics (location, occupation...) — those get replaced, never expire.', null=True)),
                ('importance', models.FloatField(default=0.5)),
                ('confidence', models.FloatField(default=0.9)),
                ('provenance', models.TextField(blank=True, default='', help_text='The sentence this came from, so the work can be checked.')),
                ('reinforced', models.PositiveIntegerField(default=0, help_text='How many times the person restated it verbatim — the only durability signal there is; consolidation promotes on it.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memory.memoryrecord')),
                ('source_conversation', models.ForeignKey(blank=True, help_text='Where this was learned. Losing the conversation keeps the memory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_records', to='conversations.conversation')),
                ('source_message', models.ForeignKey(blank=True, help_text='The user message this was extracted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_records', to='conversations.message')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memory.memoryrecord')),
                ('user', models.ForeignKey(help_text='The person this memory is about. Never cross-user.', on_delete=django.db.models.deletion.CASCADE, related_name='memory_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('patch_user', 'Patch USER.md'), ('add_fact', 'Add fact'), ('add_procedure', 'Add procedure'), ('supersede', 'Supersede'), ('ignore', 'Ignore'), ('search_sessions', 'Search sessions'), ('consolidate', 'Consolidate'), ('forget', 'Forget')], help_text='What the application actually did.', max_length=32)),
                ('proposed_action', models.CharField(choices=[('patch_user', 'Patch USER.md'), ('add_fact', 'Add fact'), ('add_procedure', 'Add procedure'), ('supersede', 'Supersede'), ('ignore', 'Ignore'), ('search_sessions', 'Search sessions'), ('consolidate', 'Consolidate'), ('forget', 'Forget')], help_text='What the model asked for. Divergence is the audit trail.', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, help_text='The rule that fired, in words a person can read.', null=True)),
                ('applied', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, default='')),
                ('source_text', models.TextField(blank=True, default='', help_text='The user message that caused this decision.')),
                ('proposal', models.JSONField(blank=True, help_text="The model's raw decision, pre-rules, for checking the work.", null=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_ledger_entries', to='conversations.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='memory.memoryrecord')),
            ],
            options={
                'verbose_name_plural': 'memory ledger entries',
            },
        ),
        migrations.CreateModel(
            name='UserMemoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='memoryrecord',
            index=models.Index(fields=['user', 'kind', 'key', 'state'], name='memrec_collision_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryrecord',
            index=models.Index(fields=['user', 'state', '-importance'], name='memrec_importance_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryrecord',
            index=models.Index(fields=['user', 'state', '-created_at'], name='memrec_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryledgerentry',
            index=models.Index(fields=['user', '-created_at'], name='memledger_scope_idx'),
        ),
    ]
