# Generated by Django 5.1.12 on 2026-08-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0005_drop_memu_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryrecord",
            name="pinned_to",
            field=models.CharField(
                blank=True,
                default="",
                help_text="USER.md heading this fact is shown under, or empty. USER.md is a VIEW of the facts pinned into it, never a second copy: the row keeps the key, the dates and the supersession, and the document renders from whatever is pinned. So a pinned fact still retires itself when a newer one arrives, and the profile follows without anyone editing markdown.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="memoryledgerentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("patch_user", "Patch USER.md"),
                    ("add_fact", "Add fact"),
                    ("add_procedure", "Add procedure"),
                    ("supersede", "Supersede"),
                    ("ignore", "Ignore"),
                    ("search_sessions", "Search sessions"),
                    ("consolidate", "Consolidate"),
                    ("forget", "Forget"),
                    ("edit", "Edit"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                ],
                help_text="What the application actually did.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="memoryledgerentry",
            name="proposed_action",
            field=models.CharField(
                choices=[
                    ("patch_user", "Patch USER.md"),
                    ("add_fact", "Add fact"),
                    ("add_procedure", "Add procedure"),
                    ("supersede", "Supersede"),
                    ("ignore", "Ignore"),
                    ("search_sessions", "Search sessions"),
                    ("consolidate", "Consolidate"),
                    ("forget", "Forget"),
                    ("edit", "Edit"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                ],
                help_text="What the model asked for. Divergence is the audit trail.",
                max_length=32,
            ),
        ),
    ]
