# Generated by Django 5.1.12 on 2026-08-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0006_pin_facts_into_the_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryrecord",
            name="applies_when",
            field=models.CharField(
                blank=True,
                default="",
                help_text="For a rule: the situations it fires in, written out. This is what the rule is embedded as, because a trigger key plus a four-word imperative has almost no semantic surface — measured, 'when:reviewing-code Be blunt' scored 0.17 against 'here is my function, take a look' and lost to an unrelated SQL rule at 0.28. Described properly the same rule scores 0.35 and wins.",
                max_length=300,
            ),
        ),
    ]
