# Generated by Django 5.1.12 on 2026-08-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0007_embed_rules_by_situation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryledgerentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("patch_user", "Patch USER.md"),
                    ("add_fact", "Add fact"),
                    ("add_procedure", "Add procedure"),
                    ("supersede", "Supersede"),
                    ("ignore", "Ignore"),
                    ("search_sessions", "Search sessions"),
                    ("consolidate", "Consolidate"),
                    ("forget", "Forget"),
                    ("edit", "Edit"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("import", "Import"),
                ],
                help_text="What the application actually did.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="memoryledgerentry",
            name="proposed_action",
            field=models.CharField(
                choices=[
                    ("patch_user", "Patch USER.md"),
                    ("add_fact", "Add fact"),
                    ("add_procedure", "Add procedure"),
                    ("supersede", "Supersede"),
                    ("ignore", "Ignore"),
                    ("search_sessions", "Search sessions"),
                    ("consolidate", "Consolidate"),
                    ("forget", "Forget"),
                    ("edit", "Edit"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("import", "Import"),
                ],
                help_text="What the model asked for. Divergence is the audit trail.",
                max_length=32,
            ),
        ),
    ]
