# Generated by Django 5.1.12 on 2026-09-01 02:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0009_alter_memoryledgerentry_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryBackfillRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        help_text="The lifecycle state of this historical memory build.",
                        max_length=16,
                    ),
                ),
                (
                    "cutoff_message_id",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="The newest assistant message included in this immutable run.",
                    ),
                ),
                ("total_turns", models.PositiveIntegerField(default=0)),
                ("processed_turns", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner whose historical conversations are being reviewed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_backfill_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="membackfill_user_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True),
                            ("is_deleted", False),
                            ("status__in", ("queued", "running")),
                        ),
                        fields=("user",),
                        name="one_active_memory_backfill_per_user",
                    )
                ],
            },
        ),
    ]
