# Generated by Django 5.1.15 on 2026-08-05 00:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0012_seed_quillmark_server"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="mcpserver",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
