# Generated by Django 5.1.12 on 2026-10-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0013_alter_mcpserver_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermcpconnection",
            name="health_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermcpconnection",
            name="health_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="usermcpconnection",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("healthy", "Healthy"),
                    ("needs_reauth", "Needs reconnect"),
                    ("unreachable", "Unreachable"),
                ],
                default="unknown",
                help_text="Last observed health, updated from real discovery/tool calls",
                max_length=20,
            ),
        ),
    ]
