# Generated by Django 5.1.12 on 2026-08-12 20:52

from django.db import migrations, models


def unlist(apps, schema_editor):
    """Take search_sessions out of the drawer.

    It is switched by the conversation's Memory toggle, which already promises
    exactly what the tool does, so a second checkbox for it did nothing on its
    own: ticked with memory off the slug was stripped from the request, and
    with memory on it was added whether or not anyone ticked it.
    """
    DareTool = apps.get_model("dare_tools", "DareTool")
    DareTool._base_manager.filter(slug="search_sessions").update(is_listed=False)


def relist(apps, schema_editor):
    DareTool = apps.get_model("dare_tools", "DareTool")
    DareTool._base_manager.filter(slug="search_sessions").update(is_listed=True)


class Migration(migrations.Migration):

    dependencies = [
        ("dare_tools", "0004_add_search_sessions_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="daretool",
            name="is_listed",
            field=models.BooleanField(
                default=True,
                help_text="Whether this tool is offered in the tool drawer. False for tools another control already owns — search_sessions belongs to the conversation's Memory toggle, so a second checkbox for it would do nothing on its own. Distinct from is_active, which means the tool can run at all: an unlisted tool still executes and still records its audit row.",
            ),
        ),
        migrations.RunPython(unlist, relist),
    ]
