# Generated by Django 5.1.15 on 2026-06-05 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchStagingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("source_candidate", "Source Candidate"),
                            ("claim", "Claim"),
                            ("note", "Note"),
                        ],
                        default="source_candidate",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField(blank=True)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("confidence_rationale", models.TextField(blank=True)),
                (
                    "evidence_label",
                    models.CharField(
                        choices=[
                            ("supporting", "Supporting"),
                            ("disputing", "Disputing"),
                            ("partial", "Partial"),
                            ("tangential", "Tangential"),
                            ("weak", "Weak"),
                            ("unverifiable", "Unverifiable"),
                        ],
                        default="unverifiable",
                        max_length=32,
                    ),
                ),
                ("citation_context", models.TextField(blank=True)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("later", "Later"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("later_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_items",
                        to="research.researchproject",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_research_staging_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_items",
                        to="research.researchsource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_staging_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchKnowledgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField(blank=True)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("confidence_rationale", models.TextField(blank=True)),
                (
                    "evidence_label",
                    models.CharField(
                        choices=[
                            ("supporting", "Supporting"),
                            ("disputing", "Disputing"),
                            ("partial", "Partial"),
                            ("tangential", "Tangential"),
                            ("weak", "Weak"),
                            ("unverifiable", "Unverifiable"),
                        ],
                        default="unverifiable",
                        max_length=32,
                    ),
                ),
                ("citation_context", models.TextField(blank=True)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("approved_at", models.DateTimeField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_research_knowledge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="research.researchproject",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_items",
                        to="research.researchsource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_knowledge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staging_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_item",
                        to="research.researchstagingitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-approved_at"],
            },
        ),
        migrations.AddIndex(
            model_name="researchstagingitem",
            index=models.Index(
                fields=["project", "status"], name="research_re_project_9d4b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchstagingitem",
            index=models.Index(
                fields=["user", "status"], name="research_re_user_id_2a206e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchstagingitem",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="research_re_is_dele_d6e606_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchknowledgeitem",
            index=models.Index(
                fields=["project", "approved_at"], name="research_re_project_d2e790_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchknowledgeitem",
            index=models.Index(
                fields=["user", "approved_at"], name="research_re_user_id_a24e99_idx"
            ),
        ),
    ]
