# Generated by Django 5.1.15 on 2026-06-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_researchstagingitem_researchknowledgeitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSoulFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_key",
                    models.CharField(
                        choices=[
                            ("research-ethics", "Research Ethics"),
                            ("empirical-rigor", "Empirical Rigor"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=64,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_soul_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="researchproject",
            name="active_soul_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="research.researchsoulfile",
            ),
        ),
        migrations.CreateModel(
            name="ResearchSoulFileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_key",
                    models.CharField(
                        choices=[
                            ("research-ethics", "Research Ethics"),
                            ("empirical-rigor", "Empirical Rigor"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=64,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_research_soul_file_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soul_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="research.researchsoulfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_soul_file_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="researchknowledgeitem",
            name="soul_file_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="knowledge_items",
                to="research.researchsoulfileversion",
            ),
        ),
        migrations.AddField(
            model_name="researchstagingitem",
            name="soul_file_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staging_items",
                to="research.researchsoulfileversion",
            ),
        ),
        migrations.AddIndex(
            model_name="researchsoulfile",
            index=models.Index(
                fields=["user", "is_default"], name="research_re_user_id_6df1e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchsoulfile",
            index=models.Index(
                fields=["user", "is_deleted"], name="research_re_user_id_3a9b0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchsoulfileversion",
            index=models.Index(
                fields=["soul_file", "version_number"],
                name="research_re_soul_fi_f9f459_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchsoulfileversion",
            index=models.Index(
                fields=["user", "created_at"], name="research_re_user_id_ddee4f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="researchsoulfileversion",
            unique_together={("soul_file", "version_number")},
        ),
    ]
