# Generated by Django 5.1.15 on 2026-06-05 13:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import research.models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_researchsoulfile_researchproject_active_soul_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchAgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "run_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("main_assistant", "Main Assistant"),
                            ("scout", "Scout"),
                            ("librarian", "Librarian"),
                            ("paper_assistant", "Paper-Specific Assistant"),
                            ("critic", "Critic"),
                            ("presentation_assistant", "Presentation Assistant"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("task", models.TextField()),
                (
                    "selected_context",
                    models.JSONField(
                        blank=True, default=research.models.default_run_selected_context
                    ),
                ),
                ("allowed_tools", models.JSONField(blank=True, default=list)),
                (
                    "capability_policy",
                    models.JSONField(
                        blank=True,
                        default=research.models.default_run_capability_policy,
                    ),
                ),
                (
                    "output_destination",
                    models.CharField(
                        choices=[
                            ("run_log", "Run Log"),
                            ("staging", "Staging"),
                            ("review_metadata", "Review Metadata"),
                            ("memory_proposals", "Memory Proposals"),
                            ("artifact_proposals", "Artifact Proposals"),
                        ],
                        default="run_log",
                        max_length=48,
                    ),
                ),
                ("external_run_id", models.CharField(blank=True, max_length=255)),
                ("status_message", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("queued_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="research.researchproject",
                    ),
                ),
                (
                    "soul_file_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="research.researchsoulfileversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchAgentToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("tool_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="succeeded",
                        max_length=24,
                    ),
                ),
                ("input_summary", models.TextField(blank=True)),
                ("output_summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tool_calls",
                        to="research.researchproject",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="research.researchagentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_agent_tool_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="researchagentrun",
            index=models.Index(
                fields=["project", "status"], name="research_re_project_f638e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchagentrun",
            index=models.Index(
                fields=["user", "status"], name="research_re_user_id_2d364e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchagentrun",
            index=models.Index(
                fields=["role", "status"], name="research_re_role_bf3e9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchagentrun",
            index=models.Index(fields=["run_id"], name="research_re_run_id_41eb2a_idx"),
        ),
        migrations.AddIndex(
            model_name="researchagenttoolcall",
            index=models.Index(
                fields=["run", "created_at"], name="research_re_run_id_6b65f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchagenttoolcall",
            index=models.Index(
                fields=["project", "tool_name"], name="research_re_project_32bb46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchagenttoolcall",
            index=models.Index(
                fields=["user", "created_at"], name="research_re_user_id_7c2128_idx"
            ),
        ),
    ]
