# Generated by Django 5.1.12 on 2026-07-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_researchthesissource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_acknowledged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When Hermes acknowledged a stop request with 'stopping'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_attempt_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of claimed upstream stop attempts.",
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When terminal Hermes truth confirmed 'cancelled'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_error_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Safe machine-readable result of the latest cancellation attempt.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_error_detail",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Safe fixed-text detail for the latest cancellation attempt.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_last_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the latest upstream stop attempt was claimed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an authorized user first requested cancellation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_stop_http_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Safe HTTP status from the latest Hermes stop response.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="cancellation_requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The authorized user who first requested cancellation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_research_run_cancellations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
