# Generated by Django 5.1.12 on 2026-07-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0015_researchagentrun_cancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchagentrun",
            name="raw_output",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The agent's exact final response text as Hermes returned it, before DARE parsing. Observability/audit only; may be backfilled from Hermes on demand while its run record is still retained.",
            ),
        ),
    ]
