# Generated by Django 5.1.12 on 2026-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0016_researchagentrun_raw_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchagentrun",
            name="reasoning_trace",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The agent's own reasoning ('reasoning.available' events) — what it read and why it chose it. Captured live from the stream; for a JSON-forced run this is the only place the thinking survives. Cannot be backfilled after the run (not part of the terminal record).",
            ),
        ),
    ]
