# Generated by Django 5.1.12 on 2026-07-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0018_researchproject_hermes_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchAgentMemorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "soul",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="SOUL.md at the time of the snapshot.",
                    ),
                ),
                (
                    "memory",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="memories/MEMORY.md at the time.",
                    ),
                ),
                (
                    "user",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="memories/USER.md at the time.",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project whose Hermes profile this snapshot came from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_memory_snapshots",
                        to="research.researchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Memory Snapshot",
                "verbose_name_plural": "Agent Memory Snapshots",
                "ordering": ["-created_at"],
            },
        ),
    ]
