# Generated by Django 5.1.12 on 2026-07-30 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0019_researchagentmemorysnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearcherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The scholar's durable facts, one per entry, in the runtime's own '§'-separated form so it can be written to USER.md verbatim.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The scholar this describes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Researcher Profile",
                "verbose_name_plural": "Researcher Profiles",
            },
        ),
    ]
