# Generated by Django 5.1.8 on 2025-04-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_file_job_id_file_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="vector_db_source",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Pinecone"), (1, "Weaviate")],
                help_text="Vector database where this file's chunks are stored",
                null=True,
                verbose_name="Vector DB Source",
            ),
        ),
    ]
