# Generated by Django 5.1.12 on 2026-07-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0015_file_syftbox_etag"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="document_model",
            field=models.JSONField(
                blank=True,
                help_text="Parsed structure: elements in reading order with their label, page, bounding box and caption.",
                null=True,
                verbose_name="Document Model",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                help_text="Text recovered at upload. Referencing a file reads this instead of re-parsing the original on every request.",
                null=True,
                verbose_name="Extracted Text",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="page_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of pages, for paginated formats such as PDF",
                null=True,
                verbose_name="Page Count",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="pages_without_text",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Pages that yielded no readable text, i.e. scans awaiting transcription",
                verbose_name="Pages Without Text",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="parser_name",
            field=models.CharField(
                blank=True,
                help_text="Parser that produced the extracted text (docling or legacy)",
                max_length=32,
                null=True,
                verbose_name="Parser",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Processing"),
                    (1, "Processed"),
                    (2, "Failed"),
                    (3, "Needs OCR"),
                ],
                default=0,
                help_text="Processing status of the file",
            ),
        ),
    ]
