# Generated by Django 5.1.12 on 2026-08-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0016_file_document_model_file_extracted_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="processing_stage",
            field=models.CharField(
                choices=[
                    ("parsing", "Analyzing document"),
                    ("enriching", "Describing visuals"),
                    ("embedding", "Creating search index"),
                    ("complete", "Complete"),
                ],
                default="parsing",
                help_text="Current ingestion phase shown while the background job runs",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DocumentEnrichmentCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_sha256", models.CharField(max_length=64)),
                ("context_sha256", models.CharField(max_length=64)),
                ("model_identifier", models.CharField(max_length=255)),
                ("prompt_version", models.CharField(max_length=32)),
                ("result", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_enrichment_cache_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="documentenrichmentcache",
            index=models.Index(
                fields=["user", "content_sha256"],
                name="doc_enrich_user_hash_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentenrichmentcache",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "content_sha256",
                    "context_sha256",
                    "model_identifier",
                    "prompt_version",
                ),
                name="unique_document_enrichment_cache_entry",
            ),
        ),
    ]
