# Generated by Django 5.1.12 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0017_document_enrichment"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="processing_journey",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Versioned processing attempts with stage timings, metrics, "
                    "and failure attribution"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="processing_stage",
            field=models.CharField(
                choices=[
                    ("parsing", "Analyzing document"),
                    ("enriching", "Describing visuals"),
                    ("embedding", "Creating embeddings"),
                    ("indexing", "Storing search index"),
                    ("complete", "Complete"),
                ],
                default="parsing",
                help_text="Current ingestion phase shown while the background job runs",
                max_length=20,
            ),
        ),
    ]
