# Generated by Django 5.1.12 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0018_file_processing_journey"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentOcrRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("partial", "Partially complete"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="awaiting_approval",
                        max_length=24,
                    ),
                ),
                ("detected_pages", models.PositiveIntegerField(default=0)),
                ("page_limit", models.PositiveIntegerField(default=0)),
                ("max_page_limit", models.PositiveIntegerField(default=100)),
                ("processed_pages", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_per_page",
                    models.DecimalField(decimal_places=8, default=0, max_digits=12),
                ),
                ("model_identifier", models.CharField(blank=True, max_length=255)),
                ("chunk_size", models.PositiveIntegerField(blank=True, null=True)),
                ("overlap_size", models.PositiveIntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_request",
                        to="files.file",
                    ),
                ),
            ],
        ),
    ]
