# Generated by Django 5.1.12 on 2026-09-02 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0020_documentocrrequest_parsed_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Position in the embedded chunk list; equals the vector id suffix."
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Original chunk content used for display and citation."
                    ),
                ),
                (
                    "element_kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("table", "Table"),
                            ("figure", "Figure"),
                            ("page_transcription", "Page transcription"),
                            ("flat", "Flat text"),
                        ],
                        default="text",
                        help_text="What the chunk is made of.",
                        max_length=32,
                    ),
                ),
                ("page_start", models.PositiveIntegerField(blank=True, null=True)),
                ("page_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "section_order",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Reading-order index of the nearest heading element.",
                        null=True,
                    ),
                ),
                ("section", models.CharField(blank=True, default="", max_length=512)),
                (
                    "heading_path",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Open headings, outermost first.",
                    ),
                ),
                ("order_start", models.PositiveIntegerField(blank=True, null=True)),
                ("order_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The file this chunk was cut from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "ordering": ["file_id", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("section", "Section"),
                            ("figure", "Figure"),
                            ("table", "Table"),
                            ("chapter", "Chapter"),
                            ("appendix", "Appendix"),
                            ("page", "Page"),
                        ],
                        max_length=16,
                    ),
                ),
                ("key", models.CharField(help_text="7.2, 3, B, 204.", max_length=64)),
                (
                    "raw_text",
                    models.CharField(help_text="The matched phrase.", max_length=200),
                ),
                (
                    "target_order",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Heading order for section, chapter and appendix targets.",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The file both ends of the pointer belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_references",
                        to="files.file",
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        help_text="The chunk containing the pointer.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_references",
                        to="files.documentchunk",
                    ),
                ),
                (
                    "target_chunk",
                    models.ForeignKey(
                        blank=True,
                        help_text="First chunk of the target section, or the figure, table or page chunk.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_references",
                        to="files.documentchunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Reference",
                "verbose_name_plural": "Document References",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["file", "section_order"], name="document_chunk_section_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("file", "chunk_index"), name="unique_document_chunk_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentreference",
            constraint=models.UniqueConstraint(
                fields=("source_chunk", "kind", "key"), name="unique_document_reference"
            ),
        ),
    ]
