# Generated by Django 5.1.12 on 2026-09-02 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0021_documentchunk_documentreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        help_text="person, organization, location, law, identifier, doi, url, accident_no, registration, certificate, date.",
                        max_length=32,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The mention as found, first occurrence.",
                        max_length=200,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Normalized form used for matching across files.",
                        max_length=200,
                    ),
                ),
                ("mentions", models.PositiveIntegerField(default=1)),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "chunk",
                    models.ForeignKey(
                        help_text="The chunk that mentions the entity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="files.documentchunk",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The file the mention belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Entity",
                "verbose_name_plural": "Document Entities",
                "ordering": ["file_id", "chunk_id", "kind", "key"],
                "indexes": [
                    models.Index(
                        fields=["file", "key"], name="document_entity_file_key_idx"
                    ),
                    models.Index(
                        fields=["kind", "key"], name="document_entity_kind_key_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chunk", "kind", "key"), name="unique_document_entity"
                    )
                ],
            },
        ),
    ]
