# Generated by Django 5.1.12 on 2026-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0022_documententity"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="index_generation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Active vector generation; empty selects the legacy index.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="ingestion_started_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Lease start for recovering interrupted ingestion attempts.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="ingestion_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Owner of the current document ingestion attempt.",
                null=True,
            ),
        ),
    ]
