# Generated by Django 5.1.12 on 2026-09-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0023_protect_document_index_replacement"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="processing_mode",
            field=models.CharField(
                choices=[
                    ("basic", "Basic (text only)"),
                    ("advanced", "Advanced (Docling)"),
                ],
                default="advanced",
                help_text="Basic extracts text only; Advanced preserves document structure with Docling where supported.",
                max_length=16,
            ),
        ),
    ]
