# Generated by Django 5.1.12 on 2026-09-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0025_normalize_basic_parser"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorIndexAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generation",
                    models.CharField(
                        help_text="Unique staged generation identifier.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "owner_id",
                    models.PositiveBigIntegerField(
                        help_text="Owner at the time of ingestion."
                    ),
                ),
                (
                    "backend",
                    models.IntegerField(
                        help_text="Vector backend used for this attempt."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="running",
                        help_text="running, empty, published, or failed.",
                        max_length=16,
                    ),
                ),
                (
                    "expected_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Expected chunks before embedding."
                    ),
                ),
                (
                    "generated_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Embedding results generated."
                    ),
                ),
                (
                    "attempted_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Vectors submitted for writing."
                    ),
                ),
                (
                    "acknowledged_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Writes explicitly acknowledged; a lower bound on interrupted batches.",
                    ),
                ),
                (
                    "verified_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Objects passing complete generation verification.",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time read-back verification succeeded.",
                        null=True,
                    ),
                ),
                (
                    "verification_seconds",
                    models.FloatField(
                        default=0,
                        help_text="Duration of read-back verification including bounded retries.",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Failure type and safe diagnostic reason."
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="File whose index is being replaced.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_attempts",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
