# Generated by Django 5.1.12 on 2026-10-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0105_backfill_energy_new_models"),
        ("files", "0027_vectorindexattempt_finished_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantKnowledgeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Admin-facing description, e.g. 'Platform user guide v3'.",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        help_text="Ingested file that holds platform documentation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_knowledge_source",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "assistant knowledge source",
                "verbose_name_plural": "assistant knowledge sources",
            },
        ),
        migrations.CreateModel(
            name="AssistantThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user started a new chat; null for the open thread.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User the thread belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "assistant thread",
                "verbose_name_plural": "assistant threads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        help_text="Who wrote the message.",
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", help_text="Message text."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("streaming", "Streaming"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped by the user"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        help_text="Lifecycle of an assistant answer; user messages are completed.",
                        max_length=16,
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Route the user was on when asking.",
                        max_length=512,
                    ),
                ),
                (
                    "tool_calls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tools the answer used: name, arguments, status, round.",
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Prompt tokens summed across tool rounds."
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Completion tokens summed across tool rounds.",
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        help_text="Model that wrote the answer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_messages",
                        to="conversations.llm",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Thread the message belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.assistantthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "assistant message",
                "verbose_name_plural": "assistant messages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="FileOrganizationProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "summary",
                    models.CharField(
                        help_text="One-line description of the plan.", max_length=500
                    ),
                ),
                (
                    "plan",
                    models.JSONField(
                        help_text="{folders: [{name, files}], tags: [{label, files}]}."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for the user"),
                            ("applied", "Applied"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending",
                        help_text="Pending until the user applies or discards it.",
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="What applying changed, and anything skipped and why.",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user applied or discarded it.",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assistant answer that presented the proposal.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="assistant.assistantmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose files the plan organises.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_organization_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "file organisation proposal",
                "verbose_name_plural": "file organisation proposals",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="assistantthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("user",),
                name="unique_open_assistant_thread",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="assistant_a_thread__b4d2bf_idx"
            ),
        ),
    ]
