"""Workflow export service.

Builds a self-contained, deterministic workflow *template* (JSON) so it can be
recreated and executed by an external runtime (e.g. a SyftBox app) with NO access
to Dare's database and NO runtime calls back to Dare.

Design notes:
- This is a template, not a data dump. We never bake file bytes, file ids, vectors
  or any Dare-specific references. Instead, each node that needs a file declares an
  upload "slot" via ``file_inputs`` and the runtime collects those files from the
  user. Embeddings, when needed, are generated by the runtime locally.
- A top-level ``required_inputs`` manifest aggregates every upload slot so the
  runtime's upload UI can list everything the workflow needs up front.
- UI-only metadata (positions, sizes, styling, selection state) is stripped, as
  are Dare DB ids (prompt id, llm id, agent id) which are meaningless externally.
- Output is deterministic: nodes/edges are sorted by id and contain no timestamps
  or volatile fields, so the same workflow always yields the same JSON.
"""
import logging

from workflows.constants import RetrievalMode
from workflows.handlers.utils.constants import NodeType
from workflows.models.nodes import build_prefetched_node_file_relations

logger = logging.getLogger(__name__)

EXPORT_SCHEMA_VERSION = "v2"

RUNTIME_NODE_TYPE = {
    NodeType.START: "start",
    NodeType.STEP: "step",
    NodeType.STRUCTURED_OUTPUT: "router",
    NodeType.FILE: "file",
    NodeType.CHAT_OUTPUT: "output",
}

EXCLUDED_NODE_TYPES = {NodeType.NOTES}


USAGE_INJECT = "inject"  # inject the file's full text into the prompt
USAGE_EMBED_RETRIEVE = "embed_and_retrieve"  # embed locally + similarity search
USAGE_BOTH = "both"  # both inject full content and embed + retrieve

FILE_NODE_USAGE = {
    RetrievalMode.EMBEDDINGS: USAGE_EMBED_RETRIEVE,
    RetrievalMode.CONTENT: USAGE_INJECT,
    RetrievalMode.BOTH: USAGE_BOTH,
}


class WorkflowExportService:
    """Serialize a Workflow into a self-contained, execution-ready JSON template."""

    def export(self, workflow) -> dict:
        all_nodes = list(workflow.nodes.all())
        excluded_ids = {
            n.node_id for n in all_nodes if n.node_type in EXCLUDED_NODE_TYPES
        }

        nodes = sorted(
            (n for n in all_nodes if n.node_type not in EXCLUDED_NODE_TYPES),
            key=lambda n: n.node_id,
        )
        edges = sorted(workflow.edges.all(), key=lambda e: e.edge_id)

        relations = build_prefetched_node_file_relations(nodes)

        exported_nodes = []
        llm_config = {}
        required_inputs = []

        for node in nodes:
            exported, used_llm, file_inputs = self._export_node(node, relations)
            exported_nodes.append(exported)
            if used_llm:
                llm_config[used_llm["identifier"]] = used_llm
            for slot in file_inputs:
                required_inputs.append(
                    {
                        "node_id": node.node_id,
                        "node_label": exported["data"].get("label", ""),
                        **slot,
                    }
                )

        exported_edges = [
            self._export_edge(e)
            for e in edges
            if e.source not in excluded_ids and e.target not in excluded_ids
        ]

        return {
            "schema_version": EXPORT_SCHEMA_VERSION,
            "workflow_id": workflow.id,
            "title": workflow.title,
            "description": workflow.description,
            "mode": workflow.mode,
            "entry_node": self._resolve_entry_node(workflow, nodes),
            "nodes": exported_nodes,
            "edges": exported_edges,
            "llm_config": llm_config,
            "required_inputs": required_inputs,
        }

    # ------------------------------------------------------------------
    # Node / edge serialization
    # ------------------------------------------------------------------

    def _export_node(self, node, relations):
        """Return (node_dict, llm_dict_or_None, [file_input_slot, ...]) for a node.

        ``file_input_slot`` entries are upload requirements (no Dare file refs);
        they are also collected into the top-level ``required_inputs`` manifest.
        """
        runtime_type = RUNTIME_NODE_TYPE.get(node.node_type, node.node_type)
        base = {"id": node.node_id, "type": runtime_type}
        data_obj = node.data_object
        used_llm = None
        file_inputs = []

        if data_obj is None:
            base["data"] = {}
            return base, used_llm, file_inputs

        if node.node_type == NodeType.STEP:
            file_inputs = self._step_file_inputs(node, data_obj, relations)
            used_llm = self._llm(data_obj.llm)
            data = {
                "label": data_obj.label,
                "prompt": self._prompt(data_obj.prompt),
                "llm": used_llm,
                "generation": {
                    "max_tokens": data_obj.max_tokens,
                    "temperature": data_obj.temperature,
                },
                "text_input": data_obj.text_input,
                "use_previous_context": data_obj.use_previous_context,
                "enable_web_search": data_obj.enable_web_search,
                "use_previous_step_files": data_obj.use_previous_step_files,
                "use_previous_step_embeddings": (
                    data_obj.use_previous_step_embeddings
                ),
                "file_inputs": file_inputs,
            }
            # Retrieval params only matter when something is embedded + retrieved.
            if any(s["usage"] == USAGE_EMBED_RETRIEVE for s in file_inputs) or (
                data_obj.use_previous_step_embeddings
            ):
                data["retrieval"] = {
                    "max_context_snippets": data_obj.max_context_snippets,
                    "similarity_threshold": data_obj.document_similarity_threshold,
                }
            base["data"] = data

        elif node.node_type == NodeType.STRUCTURED_OUTPUT:
            used_llm = self._llm(data_obj.llm)
            base["data"] = {
                "label": data_obj.label,
                "prompt": self._prompt(data_obj.prompt),
                "llm": used_llm,
                "routes": data_obj.get_routes(),
                "require_human_validation": data_obj.require_human_validation,
                "text_input": data_obj.text_input,
            }

        elif node.node_type == NodeType.FILE:
            usage = FILE_NODE_USAGE.get(data_obj.retrieval_mode, USAGE_EMBED_RETRIEVE)
            file_inputs = [{"key": "files", "usage": usage, "required": True}]
            data = {
                "label": data_obj.label,
                "file_inputs": file_inputs,
                "retrieval": {
                    "mode": data_obj.retrieval_mode,
                    "similarity_threshold": data_obj.similarity_threshold,
                    "max_results": data_obj.max_results,
                    "query_source": data_obj.query_source,
                    "include_metadata": data_obj.include_metadata,
                },
                "text_input": data_obj.text_input,
            }
            base["data"] = data

        elif node.node_type == NodeType.START:
            base["data"] = {
                "title": data_obj.title,
                "description": data_obj.description,
                "mode": data_obj.mode,
            }

        elif node.node_type == NodeType.CHAT_OUTPUT:
            base["data"] = {"label": data_obj.label}

        else:
            base["data"] = {}

        return base, used_llm, file_inputs

    def _step_file_inputs(self, node, data_obj, relations) -> list:
        """Derive upload slots for a step from its configured files.

        A slot is emitted only when the step actually needs the user to upload a
        file: i.e. files were configured for that category AND the step is not
        inheriting them from the previous step.
        """
        slots = []
        has_content = bool(relations.get_step_content_files(data_obj.id))
        has_embeddings = bool(relations.get_step_embedding_files(data_obj.id))

        if has_content and not data_obj.use_previous_step_files:
            slots.append(
                {"key": "content", "usage": USAGE_INJECT, "required": True}
            )
        if has_embeddings and not data_obj.use_previous_step_embeddings:
            slots.append(
                {
                    "key": "embeddings",
                    "usage": USAGE_EMBED_RETRIEVE,
                    "required": True,
                }
            )
        return slots

    def _export_edge(self, edge) -> dict:
        return {
            "id": edge.edge_id,
            "source": edge.source,
            "target": edge.target,
            "source_handle": edge.source_handle or None,
            "target_handle": edge.target_handle or None,
        }

    # ------------------------------------------------------------------
    # Reference resolvers
    # ------------------------------------------------------------------

    def _resolve_entry_node(self, workflow, nodes):
        if workflow.root_start_node_id and workflow.root_start_node:
            return workflow.root_start_node.node_id
        for node in nodes:
            if node.node_type == NodeType.START:
                return node.node_id
        return nodes[0].node_id if nodes else None

    def _llm(self, llm) -> dict | None:
        if not llm:
            return None
        return {
            "name": llm.name,
            "provider": llm.provider,
            "identifier": llm.identifier,
            "base_url": llm.base_url or None,
            "supports_temperature": llm.supports_temperature,
        }

    def _prompt(self, prompt) -> dict | None:
        if not prompt:
            return None
        return {
            "title": prompt.title,
            "content": prompt.content,
        }
